### ISSUE TITLE
drawing polylines on iOS safari/chrome occasianal premature draw termination

### ISSUE THREAD

**Issue by mrichardsdev** [Falke-Design/PMOrtho#9]
I have had a couple of reports from users and have tested myself, that sometimes when drawing poly-lines, when placing the second point or sometimes later points, the drawing mode terminates, it still places the point, but ends drawing. I  suspect that the touch is sometimes being interpenetrated as 2 'clicks'

this is happening inside my project and also the demo. i find it is happening about 1 in 4 times i try to draw a line so should be easy to replicate.

I have not been able to get geoman on its own to do it at all.

**Comment by Falke-Design** [comment]
This is a problem of Leaflet-Core https://github.com/Leaflet/Leaflet/issues/7255
Stackoverflow: https://stackoverflow.com/a/65369228/8283938
